name: booking_system
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bubble_bottom_bar: ^2.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_share: ^2.0.0
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+4
  in_app_review: ^2.0.3
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  skeleton_text: ^3.0.0
  sqflite: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/
    - assets/gif/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
